package com.mrojas.serpientes_escaleras.ventanas;

import com.mrojas.serpientes_escaleras.jugador.Jugador;
import com.mrojas.serpientes_escaleras.tablero.Partida;
import com.mrojas.serpientes_escaleras.tablero.Tablero;
import com.mrojas.serpientes_escaleras.ventanas.paneles_partida.PanelTablero;
import com.mrojas.serpientes_escaleras.ventanas.static_image.ImagenStatic;
import java.awt.BorderLayout;
import javax.swing.*;

/**
 * Clase encargada de mostrar graficamente la partida del juego
 *
 * @author Manuel Rojas
 */
public class VentanaPartida2 extends javax.swing.JFrame {

    private Tablero tablero;
    private Partida partida;
    private Jugador[] jugadores;
    private int jugadorTurno = 0;
    private int cantDado1 = 0, cantDado2 = 0;

    public VentanaPartida2(Jugador[] jugadores) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
        setLocationRelativeTo(null);
        this.jugadores = jugadores;
        this.tablero = new Tablero(10, 10);
        partida = new Partida(jugadores, this.tablero);
        cambiarEtiqueta(jugadores[0]);
        add(new PanelTablero(this.tablero), BorderLayout.CENTER);
        asignarEtiquetas();
        cambiarDado(6, 6);

    }

    private void asignarEtiquetas() {
        JLabel[] etiquetas = {etiquetaJugador1, etiquetaJugador2, etiquetaJugador3, etiquetaJugador4, etiquetaJugador5, etiquetaJugador6};
        for (int i = 0; i < jugadores.length; i++) {
            etiquetas[i].setText(jugadores[i].toString());
            etiquetas[i].setIcon(jugadores[i].getFicha().getImagen());

        }
    }

    public void cambiarDado(int cant1, int cant2) {
        cambiarDado(cant1, etiquetaDado1);
        cambiarDado(cant2, etiquetaDado2);
    }

    private void cambiarDado(int cara, JLabel dado) {
        switch (cara) {
            case 1 -> {
                dado.setIcon(ImagenStatic.getImagenDimensionada(CARA1, 100, 100));
            }
            case 2 -> {
                dado.setIcon(ImagenStatic.getImagenDimensionada(CARA2, 100, 100));
            }
            case 3 -> {
                dado.setIcon(ImagenStatic.getImagenDimensionada(CARA3, 100, 100));
            }
            case 4 -> {
                dado.setIcon(ImagenStatic.getImagenDimensionada(CARA4, 100, 100));
            }
            case 5 -> {
                dado.setIcon(ImagenStatic.getImagenDimensionada(CARA5, 100, 100));
            }
            case 6 -> {
                dado.setIcon(ImagenStatic.getImagenDimensionada(CARA6, 100, 100));
            }
        }
    }

    private void siguienteTurno() {
        jugadorTurno++;
        if (jugadorTurno >= jugadores.length) {
            jugadorTurno = 0;
        }
    }

    private void cambiarEtiqueta(Jugador j1) {
        jLabel3.setText("Es el turno de: " + j1);
    }
    
    private void terminarPartida(){
        if(partida.terminarPartida()){
            String mensaje = "Felicidades " + partida.getGanador() + "\n has ganado la partida!";
            JOptionPane.showMessageDialog(this, mensaje, "Juego terminado", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInfoJugadores = new javax.swing.JPanel();
        etiquetaJugador1 = new javax.swing.JLabel();
        etiquetaJugador3 = new javax.swing.JLabel();
        etiquetaJugador2 = new javax.swing.JLabel();
        etiquetaJugador4 = new javax.swing.JLabel();
        etiquetaJugador5 = new javax.swing.JLabel();
        etiquetaJugador6 = new javax.swing.JLabel();
        jPanelDados = new javax.swing.JPanel();
        etiquetaDado1 = new javax.swing.JLabel();
        etiquetaDado2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        botonMoverFicha = new javax.swing.JButton();
        jPanelEncabezado = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("En partida");

        jPanelInfoJugadores.setPreferredSize(new java.awt.Dimension(350, 600));

        etiquetaJugador1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        etiquetaJugador1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        etiquetaJugador3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        etiquetaJugador3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        etiquetaJugador2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        etiquetaJugador2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        etiquetaJugador4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        etiquetaJugador4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        etiquetaJugador5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        etiquetaJugador5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        etiquetaJugador6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        etiquetaJugador6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanelInfoJugadoresLayout = new javax.swing.GroupLayout(jPanelInfoJugadores);
        jPanelInfoJugadores.setLayout(jPanelInfoJugadoresLayout);
        jPanelInfoJugadoresLayout.setHorizontalGroup(
            jPanelInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoJugadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaJugador3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(etiquetaJugador2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(etiquetaJugador4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(etiquetaJugador6, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(etiquetaJugador5, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelInfoJugadoresLayout.setVerticalGroup(
            jPanelInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoJugadoresLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(etiquetaJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaJugador5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaJugador6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelInfoJugadores, java.awt.BorderLayout.WEST);

        jPanelDados.setPreferredSize(new java.awt.Dimension(300, 119));
        jPanelDados.setLayout(new java.awt.BorderLayout());

        etiquetaDado1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiquetaDado1.setMaximumSize(new java.awt.Dimension(200, 200));
        etiquetaDado1.setMinimumSize(new java.awt.Dimension(100, 100));
        etiquetaDado1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanelDados.add(etiquetaDado1, java.awt.BorderLayout.WEST);

        etiquetaDado2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiquetaDado2.setMaximumSize(new java.awt.Dimension(200, 200));
        etiquetaDado2.setMinimumSize(new java.awt.Dimension(100, 100));
        etiquetaDado2.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanelDados.add(etiquetaDado2, java.awt.BorderLayout.EAST);

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(40, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(40, 16));
        jLabel3.setPreferredSize(new java.awt.Dimension(40, 16));
        jPanelDados.add(jLabel3, java.awt.BorderLayout.NORTH);

        jPanel2.setMinimumSize(new java.awt.Dimension(133, 150));
        jPanel2.setPreferredSize(new java.awt.Dimension(312, 150));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton1.setText("¡TIRAR LOS DADOS!");
        jButton1.setMaximumSize(new java.awt.Dimension(133, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(133, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(133, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, java.awt.BorderLayout.PAGE_START);

        botonMoverFicha.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        botonMoverFicha.setText("¡MOVER FICHA!");
        botonMoverFicha.setMaximumSize(new java.awt.Dimension(75, 50));
        botonMoverFicha.setMinimumSize(new java.awt.Dimension(75, 50));
        botonMoverFicha.setPreferredSize(new java.awt.Dimension(75, 50));
        botonMoverFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMoverFichaActionPerformed(evt);
            }
        });
        jPanel2.add(botonMoverFicha, java.awt.BorderLayout.SOUTH);

        jPanelDados.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelDados, java.awt.BorderLayout.EAST);

        jPanelEncabezado.setPreferredSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout jPanelEncabezadoLayout = new javax.swing.GroupLayout(jPanelEncabezado);
        jPanelEncabezado.setLayout(jPanelEncabezadoLayout);
        jPanelEncabezadoLayout.setHorizontalGroup(
            jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1051, Short.MAX_VALUE)
        );
        jPanelEncabezadoLayout.setVerticalGroup(
            jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelEncabezado, java.awt.BorderLayout.NORTH);

        jPanel1.setPreferredSize(new java.awt.Dimension(1051, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1051, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cantDado1 = partida.tirarDado();
        cantDado2 = partida.tirarDado();
        cambiarDado(cantDado1, cantDado2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonMoverFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMoverFichaActionPerformed
        if (cantDado1 > 0 && cantDado2 > 0) {
            partida.mueveJugador(jugadores[jugadorTurno], cantDado1 + cantDado2);
            terminarPartida();
            cantDado1 = 0;
            cantDado2 = 0;
            siguienteTurno();
            cambiarEtiqueta(jugadores[jugadorTurno]);
        } else {
            JOptionPane.showMessageDialog(this, "No se han tirado los dados", "No se puede mover", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonMoverFichaActionPerformed

    private final ImageIcon CARA1 = new ImageIcon(getClass().getResource("/images/dadoCara1.png"));
    private final ImageIcon CARA2 = new ImageIcon(getClass().getResource("/images/dadoCara2.png"));
    private final ImageIcon CARA3 = new ImageIcon(getClass().getResource("/images/dadoCara3.png"));
    private final ImageIcon CARA4 = new ImageIcon(getClass().getResource("/images/dadoCara4.png"));
    private final ImageIcon CARA5 = new ImageIcon(getClass().getResource("/images/dadoCara5.png"));
    private final ImageIcon CARA6 = new ImageIcon(getClass().getResource("/images/dadoCara6.png"));
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMoverFicha;
    private javax.swing.JLabel etiquetaDado1;
    private javax.swing.JLabel etiquetaDado2;
    private javax.swing.JLabel etiquetaJugador1;
    private javax.swing.JLabel etiquetaJugador2;
    private javax.swing.JLabel etiquetaJugador3;
    private javax.swing.JLabel etiquetaJugador4;
    private javax.swing.JLabel etiquetaJugador5;
    private javax.swing.JLabel etiquetaJugador6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDados;
    private javax.swing.JPanel jPanelEncabezado;
    private javax.swing.JPanel jPanelInfoJugadores;
    // End of variables declaration//GEN-END:variables
}
