package com.mrojas.serpientes_escaleras.ventanas;

import com.mrojas.serpientes_escaleras.jugador.VectorJugador;
import com.mrojas.serpientes_escaleras.ventanas.panel_jugadores.VentanaJugador;
import com.mrojas.serpientes_escaleras.ventanas.paneles_partida.VentanaSeleccion;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Esta clase sirve como primera comunicación con el usuario graficamente, en
 * ella se presenta el menú principal
 *
 * @author Manuel Rojas
 */
public class VentanaMenuInicio extends javax.swing.JFrame {

    VectorJugador jugadores;

    public VentanaMenuInicio() {
        jugadores = new VectorJugador();
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/snake.png")).getImage());
        setVisible(true);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        botonJugar = new javax.swing.JButton();
        botonJugadores = new javax.swing.JButton();
        botonReportes = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        botonJugar.setFont(new java.awt.Font("Poppins ExtraBold", 0, 24)); // NOI18N
        botonJugar.setText("NUEVA PARTIDA");
        botonJugar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });

        botonJugadores.setFont(new java.awt.Font("Poppins ExtraBold", 0, 24)); // NOI18N
        botonJugadores.setText("JUGADORES");
        botonJugadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugadoresActionPerformed(evt);
            }
        });

        botonReportes.setFont(new java.awt.Font("Poppins ExtraBold", 0, 24)); // NOI18N
        botonReportes.setText("REPORTES");
        botonReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReportesActionPerformed(evt);
            }
        });

        botonSalir.setFont(new java.awt.Font("Poppins ExtraBold", 0, 24)); // NOI18N
        botonSalir.setText("SALIR");
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
        });
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins Black", 1, 14)); // NOI18N
        jLabel1.setText("BIENVENIDO A");

        jLabel2.setFont(new java.awt.Font("Poppins ExtraBold", 0, 36)); // NOI18N
        jLabel2.setText("SERPIENTES Y ESCALERAS");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botonJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(0, 79, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(245, 245, 245))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(botonJugar)
                .addGap(18, 18, 18)
                .addComponent(botonJugadores)
                .addGap(18, 18, 18)
                .addComponent(botonReportes)
                .addGap(18, 18, 18)
                .addComponent(botonSalir)
                .addGap(90, 90, 90))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportesActionPerformed
        if (jugadores.getSize() > 0) {
            new VentanaReportes(jugadores);
        } else {
            JOptionPane.showMessageDialog(this, "No hay jugadores registrados para mostrar reportes", "Reportes", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_botonReportesActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed

    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
        int salir = JOptionPane.showConfirmDialog(this, "¿Esta seguro que quiere salir?", "Salir", JOptionPane.YES_NO_OPTION);
        if (salir == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_botonSalirMouseClicked

    private void botonJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugadoresActionPerformed
        new VentanaJugador(jugadores);
    }//GEN-LAST:event_botonJugadoresActionPerformed

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
        if (jugadores.getSize() > 1) {
            new VentanaSeleccion(jugadores);
        } else {
            JOptionPane.showMessageDialog(this, "No hay jugadores suficientes para una partida", "Nueva partida", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_botonJugarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonJugadores;
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonReportes;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
