package com.mrojas.serpientes_escaleras.ventanas.panel_jugadores;

import javax.swing.ImageIcon;

import com.mrojas.serpientes_escaleras.archivos.ManejoArchivo;
import com.mrojas.serpientes_escaleras.jugador.VectorJugador;
import javax.swing.JOptionPane;

/**
 * Clase que se encarga de controlar el registro, edición, eliminación de
 * jugadores Así como tambien el guardado de archivos y carga de datos de manera
 * interactiva con el usuario
 *
 * @author Manuel Rojas
 */
public class VentanaJugador extends javax.swing.JFrame {

    private VectorJugador jugadores;
    private int fila = -1;

    public VentanaJugador(VectorJugador jugadores) {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/snake.png")).getImage());
        this.jugadores = jugadores;
        if (jugadores.getSize() > 0) {
            actualizarTabla();
        } else {
            activarBotones(false);
        }
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public VectorJugador getJugadores() {
        return jugadores;
    }

    private void activarBotones(boolean activar) {
        botonGuardar.setEnabled(activar);
        botonEditar.setEnabled(activar);
        botonEliminar.setEnabled(activar);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableJugador = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        botonRegistro = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        botonCargar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jugadores");
        setMinimumSize(new java.awt.Dimension(720, 512));
        setPreferredSize(new java.awt.Dimension(720, 512));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JUGADORES DE SERPIENTES Y ESCALERAS");
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 475));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(530, 100));

        jTableJugador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre y Apellido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableJugador.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableJugadorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableJugador);
        if (jTableJugador.getColumnModel().getColumnCount() > 0) {
            jTableJugador.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableJugador.getColumnModel().getColumn(1).setPreferredWidth(220);
        }

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 475));

        botonRegistro.setFont(new java.awt.Font("Poppins Black", 0, 14)); // NOI18N
        botonRegistro.setText("NUEVO JUGADOR");
        botonRegistro.setMaximumSize(new java.awt.Dimension(300, 50));
        botonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroActionPerformed(evt);
            }
        });

        botonEditar.setFont(new java.awt.Font("Poppins Black", 0, 14)); // NOI18N
        botonEditar.setText("EDITAR");
        botonEditar.setMaximumSize(new java.awt.Dimension(300, 50));
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonEliminar.setFont(new java.awt.Font("Poppins Black", 0, 14)); // NOI18N
        botonEliminar.setText("ELIMINAR");
        botonEliminar.setMaximumSize(new java.awt.Dimension(300, 50));
        botonEliminar.setMinimumSize(new java.awt.Dimension(110, 28));
        botonEliminar.setPreferredSize(new java.awt.Dimension(110, 28));
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonVolver.setFont(new java.awt.Font("Poppins Black", 0, 14)); // NOI18N
        botonVolver.setText("VOLVER");
        botonVolver.setMaximumSize(new java.awt.Dimension(300, 50));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonCargar.setFont(new java.awt.Font("Poppins Black", 0, 14)); // NOI18N
        botonCargar.setText("CARGAR");
        botonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarActionPerformed(evt);
            }
        });

        botonGuardar.setFont(new java.awt.Font("Poppins Black", 0, 14)); // NOI18N
        botonGuardar.setText("GUARDAR");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonCargar)
                                .addGap(18, 18, 18)
                                .addComponent(botonGuardar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(botonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        ManejoArchivo.guardarArchivoJugadores(this.jugadores.getListaJugadores(), ManejoArchivo.getFileChooserPath());
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed
        new VentanaRegistro(this);
        activarBotones(true);
    }//GEN-LAST:event_botonRegistroActionPerformed

    private void jTableJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableJugadorMouseClicked
        fila = jTableJugador.getSelectedRow();
    }//GEN-LAST:event_jTableJugadorMouseClicked

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        if (fila > -1) {
            int seguro = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar a " + jugadores.getJugador(fila) + "?", "Eliminar jugador", JOptionPane.YES_NO_OPTION);
            if (seguro == 0) {
                jugadores.eliminarJugador(fila);
                actualizarTabla();
            }
            fila = -1;
        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún jugador", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
        if (jugadores.getSize() < 1) {
            activarBotones(false);
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        if (fila > -1) {
            new VentanaRegistro(fila, this);
            fila = -1;
        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún jugador", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarActionPerformed
        jugadores.setListaJugadores(ManejoArchivo.cargarArchivoJugadores(ManejoArchivo.getFileChooserPath()));
        actualizarTabla();
    }//GEN-LAST:event_botonCargarActionPerformed

    public void actualizarTabla() {
        Object[][] datos = new Object[jugadores.getSize()][2];

        for (int i = 0; i < jugadores.getSize(); i++) {
            datos[i][0] = jugadores.getJugador(i).getId();
            datos[i][1] = jugadores.getJugador(i);
        }

        jTableJugador.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                    "ID", "Nombre y Apellido"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableJugador;
    // End of variables declaration//GEN-END:variables
}
